# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

##########################################################################################################
# This configuration will install the tools necessary to get started with C# development on Windows      #
# Reference: https://learn.microsoft.com/visualstudio/get-started/csharp/tutorial-console                #
#                                                                                                        #
# This will:                                                                                             #
#     * Enable Developer Mode                                                                            #
#     * Install GitHub Desktop                                                                           #
#     * Install Visual Studio Community 2022                                                             #
#     * Install Managed Desktop Workload to Visual Studio Community 2022                                 #
#     * Install Universal Workload to Visual Studio Community 2022                                       #
#                                                                                                        #
##########################################################################################################
properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: Enable
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHub Desktop
      directives:
        description: Install GitHub Desktop
        allowPrerelease: true
      settings:
        id: GitHub.GitHubDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Visual Studio
      directives:
        description: Install Visual Studio 2022 Community
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: Workloads ManagedDesktop
      dependsOn:
        - Visual Studio
      directives:
        description: Install required VS Workloads (ManagedDesktop)
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release                  
        components:
          - Microsoft.VisualStudio.Workload.ManagedDesktop
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: Workloads Universal
      dependsOn:
        - Visual Studio
      directives:
        description: Install required VS Workloads (Universal)
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release                  
        components:
          - Microsoft.VisualStudio.Workload.Universal
  configurationVersion: 0.2.0