id: labelManagement.issueUpdated
name: GitOps.PullRequestIssueManagement
description: >-
  Handlers for when an issue is updated and not closed
  This primarily includes handlers for comments, reviews, and re-runs
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Remove "No-Recent-Activity" when a pull request or issue is updated
        if:
          - or:
              - payloadType: Pull_Request
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
              - payloadType: Issues
          - not:
              isAction:
                action: Closed
          - hasLabel:
              label: No-Recent-Activity
        then:
          - removeLabel:
              label: No-Recent-Activity
        # The policy service should not trigger itself here, or else the label would be removed immediately after being added
        triggerOnOwnActions: False
      - description: Clean email replies on every comment
        if:
          - payloadType: Issue_Comment
        then:
          - cleanEmailReply
      - description: Sync labels with issues on all pull request events
        if:
          - or:
              - payloadType: Pull_Request
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
          - not:
              isAction:
                action: Closed
        then:
          - labelSync:
              pattern: Blocking-Issue
          - inPrLabel:
              label: In-PR
      - description: Remove "Help-Wanted" label when an issue goes into PR
        if:
          - payloadType: Issues
          - labelAdded:
              label: In-PR
          - hasLabel:
              label: Help-Wanted
        then:
          - removeLabel:
              label: Help-Wanted
        # The policy service should trigger even when the update was initiated by the policy service
        triggerOnOwnActions: true
      - description: >-
          If an author responds to an issue which needs author feedback
          * Remove the Needs-Author-Feedback Label
          * Add the Needs-Attention Label
        if:
          - or:
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - isActivitySender:
              issueAuthor: True
          - hasLabel:
              label: Needs-Author-Feedback
          - not:
              isAction:
                action: Synchronize
        then:
          - removeLabel:
              label: Needs-Author-Feedback
          - addLabel:
              label: Needs-Attention # This will automatically assign the ICM Users
      - description: >-
          When changes are requested on a pull request
          * Disable automerge
          * Label with Changes-Requested
        if:
          - payloadType: Pull_Request_Review
          - isAction:
              action: Submitted
          - isReviewState:
              reviewState: Changes_requested
        then:
          - disableAutoMerge
          - addLabel:
              label: Changes-Requested
      - description: Remove status labels when a PR is synchronized (new commits pushed)
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Synchronize
        then:
          - removeLabel:
              label: Azure-Pipeline-Passed
          - removeLabel:
              label: Blocking-Issue
          - removeLabel:
              label: Changes-Requested
          # - removeLabel:
          #     label: Moderator-Approved
          - removeLabel:
              label: Needs-Attention
          - removeLabel:
              label: Needs-Author-Feedback
          - removeLabel:
              label: Unexpected-File
      - description: Remove status labels when a PR is re-run
        if:
          - payloadType: Issue_Comment
          - or:
              - commentContains:
                  pattern: '\/[a|A][z|Z][p|P] [r|R][u|U][n|N]'
                  isRegex: True
              - commentContains:
                  pattern: '\/[a|A][z|Z][u|U][r|R][e|E][p|P][i|I][p|P][e|E][l|L][i|I][n|N][e|E][s|S] [r|R][u|U][n|N]'
                  isRegex: True
          - not:
              isActivitySender:
                user: microsoft-github-policy-service[bot]
                issueAuthor: False
          - or:
              - activitySenderHasPermission:
                  permission: Admin
              - activitySenderHasPermission:
                  permission: Write
        then:
          # Don't remove Changes-Requested here because it is just a re-run, no new commits have been added
          - removeLabel:
              label: Author-Not-Authorized
          - removeLabel:
              label: Azure-Pipeline-Passed
          - removeLabel:
              label: Blocking-Issue
          - removeLabel:
              label: Needs-Attention
          - removeLabel:
              label: Needs-Author-Feedback
          - removeLabel:
              label: Project-File
onFailure:
onSuccess:
