id: labelManagement.issueOpened
name: GitOps.PullRequestIssueManagement
description: Handlers for when an issue is first opened
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          When a PR is opened/updated, if no files are modified
          * Close the issue
          * Add a comment
        if:
          - payloadType: Pull_Request
          - isOpen
          - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Synchronize
          - filesMatchPattern:
              pattern: ^$
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},


                This pull request does not update any files. Please review your commit history and resubmit.


                Template: msftbot/validationError/pullRequest/noContent
          - closePullRequest
      - description: Add CodeFlow link to new PRs
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - addCodeFlowLink
          # If the user is a first-time contributor, add the Needs-CLA Label
          - if:
              - activitySenderHasAssociation:
                  association: FIRST_TIME_CONTRIBUTOR
            then:
              - addLabel:
                  label: Needs-CLA
      - description: Add Needs-Triage to new issues
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
        then:
          - addLabel:
              label: Needs-Triage
      - description: >-
          When a pull request is opened, if the files match DevOpsPipelineDefinitions/*
          * Add a message to the author
          * Assign to the author
          * Add the "Needs-Author-Feedback" label
      - description: >-
          When a PR is opened/updated, if the content is in a project folder and user is not repo admin
          * Add Project-File label
        if:
          - payloadType: Pull_Request
          - isOpen
          - not:
              filesMatchPattern:
                pattern: ^$
          - or:
              - filesMatchPattern:
                  pattern: ^\.?[\\\/]?.github[\\\/].*
              - filesMatchPattern:
                  pattern: ^\.?[\\\/]?.configurations[\\\/].*
              - filesMatchPattern:
                  pattern: ^\.?[\\\/]?.vscode[\\\/].*
              - filesMatchPattern:
                  pattern: ^\.?[\\\/]?doc[\\\/].*
              - filesMatchPattern:
                  pattern: ^\.?[\\\/]?Tools[\\\/].*
              - filesMatchPattern:
                  pattern: ^.*\.md$
              - filesMatchPattern:
                  pattern: ^.gitattributes$
              - filesMatchPattern:
                  pattern: ^.gitignore$
              - filesMatchPattern:
                  pattern: ^.editorconfig$
              - filesMatchPattern:
                  pattern: ^LICENSE$
          - not:
              activitySenderHasPermission:
                permission: Admin
        then:
          - addLabel:
              label: Project-File
      - description: >-
          When a PR is opened/updated, if the content is in the pipelines and user is not repo admin
          * Add Author-Not-Authorized label
        if:
          - payloadType: Pull_Request
          - isOpen
          - not:
              filesMatchPattern:
                pattern: ^$
          - filesMatchPattern:
              pattern: ^pipelines\\.*
          - not:
              activitySenderHasPermission:
                permission: Admin
        then:
          - addLabel:
              label: Author-Not-Authorized
onFailure:
onSuccess:
