id: moderatorTriggers
name: GitOps.PullRequestIssueManagement
description: Defines the users and permissions for the moderators
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          # If the activity sender is any one of the moderators, has Admin permission on the repo, or has Write permissions on the repo. . .
          - or:
              - activitySenderHasPermission:
                  permission: Admin
              - activitySenderHasPermission:
                  permission: Write
              - isActivitySender:
                  user: stephengillie
                  issueAuthor: False
              - isActivitySender:
                  user: Trenly
                  issueAuthor: False
              - isActivitySender:
                  user: mdanish-kh
                  issueAuthor: False
              - isActivitySender:
                  user: russellbanks
                  issueAuthor: False
        then:
          # If the payload is an issue_Comment or a Pull_Request_Review_Comment
          - if:
              - or:
                  - payloadType: Issue_Comment
                  - payloadType: Pull_Request_Review_Comment
            # Remove the Needs-Triage label
            # Take different actions based on the comment pattern
            then:
              - removeLabel:
                  label: Needs-Triage
              # Area-Bots
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[aA]rea[\s-][bB]ots'
                      isRegex: True
                then:
                  - addLabel:
                      label: Area-Bots
              # Area-Validation-Pipeline
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[aA]rea[\s-][vV]alidation[\s-][pP]ipeline'
                      isRegex: True
                then:
                  - addLabel:
                      label: Area-Validation-Pipeline
              # Blocking-Issue
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[bB]locking[\s-][iI]ssue'
                      isRegex: True
                then:
                  - removeLabel:
                      label: Needs-Author-Feedback
                  - removeLabel:
                      label: Needs-Attention
                  - addLabel:
                      label: Blocking-Issue
              # GitDsc
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Gg]it[Dd][Ss][Cc]'
                      isRegex: True
                then:
                  - addLabel:
                      label: GitDsc
              # Help-Wanted
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[hH]elp[\s-][wW]anted'
                      isRegex: True
                then:
                  - addLabel:
                      label: Help-Wanted
              # In-PR
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Ii]n[\s-][Pp][Rr]'
                      isRegex: True
                then:
                  - addLabel:
                      label: In-PR
              # Issue-Bug
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[iI]ssue[\s-][bB]ug'
                      isRegex: True
                then:
                  - addLabel:
                      label: Issue-Bug
              # Issue-Docs
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[iI]ssue[\s-][dD]ocs'
                      isRegex: True
                then:
                  - addLabel:
                      label: Issue-Docs
              # Issue-Feature
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[iI]ssue[\s-][fF]eature'
                      isRegex: True
                then:
                  - addLabel:
                      label: Issue-Feature
              # Microsoft.DotNet.Dsc
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Dd]ot[Nn]et\.[Dd][Ss][Cc]'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.DotNet.Dsc
              # Microsoft.VSCode.Dsc
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Vv][Ss][Cc]ode\.[Dd][Ss][Cc]'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.VSCode.Dsc
              # Microsoft.Windows.Developer
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Ww]indows\.[Dd]eveloper'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.Windows.Developer
              # Microsoft.Windows.Setting.Accessibility
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Ww]indows\.[Ss]ettings?\.[Aa]ccessibility'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.Windows.Setting.Accessibility
              # Microsoft.Windows.Settings
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Ww]indows\.[Ss]ettings'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.Windows.Settings
              # Microsoft.Windows.Setting.Language
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Ww]indows\.[Ss]ettings?\.[Ll]anguage'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.Windows.Setting.Language
              # Microsoft.Windows.Setting.System
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Ww]indows\.[Ss]ettings?\.[Ss]ystem'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.Windows.Setting.System
              # Microsoft.Windows.Setting
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Mm]icrosoft\.[Ww]indows\.[Ss]ettings?'
                      isRegex: True
                then:
                  - addLabel:
                      label: Microsoft.Windows.Setting
              # Moderator-Approved
              # - if:
              #       - commentContains:
              #             pattern: '\[[Pp]olicy\]\s+[mM]oderator[\s-][Aa]pproved'
              #             isRegex: True
              #   then:
              #       - addLabel:
              #             label: Moderator-Approved
              # Needs-Attention
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Nn]eeds[\s-][Aa]ttention'
                      isRegex: True
                then:
                  - addLabel:
                      label: Needs-Attention
                  - addReply:
                      reply: >-
                        Hello ${issueAuthor},


                        Your pull request requires attention from a repository administrator. It has been assigned to a developer for review.


                        Template: msftbot/manualReview
              # Needs-Author-Feedback
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Nn]eeds[\s-][Aa]uthor[\s-][fF]eedback'
                      isRegex: True
                then:
                  - addLabel:
                      label: Needs-Author-Feedback
              # Needs-CLA
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Nn]eeds[\s-][Cc][Ll][Aa]'
                      isRegex: True
                then:
                  - addLabel:
                      label: Needs-CLA
              # New-DSC-Resource
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Nn]ew[\s-][Dd][Ss][Cc][\s-][Rr]esource'
                      isRegex: True
                then:
                  - addLabel:
                      label: New-DSC-Resource
              # NpmDsc
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Nn][Pp][Mm]\.[Dd][Ss][Cc]'
                      isRegex: True
                then:
                  - addLabel:
                      label: NpmDsc
              # PythonPip3Dsc
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Pp]ython[Pp]ip3?[Dd][Ss][Cc]'
                      isRegex: True
                then:
                  - addLabel:
                      label: PythonPip3Dsc
              # PSA
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Pp][Ss][Aa]'
                      isRegex: True
                then:
                  - addLabel:
                      label: Public-Service-Announcement
              # YarnDsc
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[Yy]arn[Dd][Ss][Cc]'
                      isRegex: True
                then:
                  - addLabel:
                      label: YarnDsc
              # Unblocked
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[uU]nblocked'
                      isRegex: True
                then:
                  - removeLabel:
                      label: Blocking-Issue
              # Reset-Feedback
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[rR]eset\s+[fF]eedback'
                      isRegex: True
                then:
                  - removeLabel:
                      label: Needs-Author-Feedback
                  - removeLabel:
                      label: Needs-Attention
                  #   - removeLabel:
                  #         label: Moderator-Approved
                  - removeLabel:
                      label: Changes-Requested
              # Reset-Labels
              - if:
                  - commentContains:
                      pattern: '\[[Pp]olicy\]\s+[rR]eset[\s-]+[lL]abels'
                      isRegex: True
                then:
                  - removeLabel:
                      label: Area-Bots
                  - removeLabel:
                      label: Area-Validation-Pipeline
                  - removeLabel:
                      label: Blocking-Issue
                  - removeLabel:
                      label: Changes-Requested
                  - removeLabel:
                      label: GitDsc
                  - removeLabel:
                      label: Help-Wanted
                  - removeLabel:
                      label: In-PR
                  - removeLabel:
                      label: Issue-Bug
                  - removeLabel:
                      label: Issue-Docs
                  - removeLabel:
                      label: Issue-Feature
                  - removeLabel:
                      label: Microsoft.DotNet.Dsc
                  - removeLabel:
                      label: Microsoft.VSCode.Dsc
                  - removeLabel:
                      label: Microsoft.Windows.Developer
                  - removeLabel:
                      label: Microsoft.Windows.Setting.Accessibility
                  - removeLabel:
                      label: Microsoft.Windows.Setting.Language
                  - removeLabel:
                      label: Microsoft.Windows.Setting.System
                  - removeLabel:
                      label: Microsoft.Windows.Setting
                  #   - removeLabel:
                  #         label: Moderator-Approved
                  - removeLabel:
                      label: Needs-Attention
                  - removeLabel:
                      label: Needs-Author-Feedback
                  - removeLabel:
                      label: Needs-CLA
                  - removeLabel:
                      label: New-DSC-Resource
                  - removeLabel:
                      label: NpmDsc
                  - removeLabel:
                      label: Project-File
                  - removeLabel:
                      label: Public-Service-Announcement
                  - removeLabel:
                      label: PythonPip3Dsc
                  - removeLabel:
                      label: YarnDsc
                  ## TODO: Dismiss All Pull Request Reviews
              # Duplicate of #
              - if:
                  - commentContains:
                      pattern: Duplicate\s+of\s+\#?\s*\d+
                      isRegex: True
                then:
                  - addReply:
                      reply: >-
                        Hello @${issueAuthor},


                        We've identified this as a duplicate of another issue or PR that already exists. This specific instance is being closed in favor of the linked issue. Please add your 👍 to the other issue to raise its priority. Thanks for your contribution!


                        Template: msftbot/duplicate/closed
                  - closeIssue
                  - removeLabel:
                      label: Needs-Triage
                  - removeLabel:
                      label: Needs-Attention
                  - removeLabel:
                      label: Needs-Author-Feedback
                  - addLabel:
                      label: Resolution-Duplicate
              # Close with reason <>;
              - if:
                  - commentContains:
                      pattern: "[cC]lose\\s+[wW]ith\\s+[rR]eason\\s*:[\\w\\s\\-\\(\\)\\[\\]\\{\\}\\\\\\/.+=@\\#$%&^*`~|'\",<>?]*(?=;)"
                      isRegex: True
                then:
                  - closeIssue
                  - removeLabel:
                      label: Needs-Triage
                  - removeLabel:
                      label: Needs-Attention
                  - removeLabel:
                      label: Needs-Author-Feedback
              # Reopen with reason <>;
              - if:
                  - commentContains:
                      pattern: "[rR]eopen\\s+[wW]ith\\s+[rR]eason\\s*:[\\w\\s\\-\\(\\)\\[\\]\\{\\}\\\\\\/.+=@\\#$%&^*`~|'\",<>?]*(?=;)"
                      isRegex: True
                then:
                  - reopenIssue
                  - removeLabel:
                      label: Resolution-Duplicate
                  - removeLabel:
                      label: No-Recent-Activity
          # If the payload is a Pull_Request_Review and an approval, add the Moderator-Approved label
        #   - if:
        #       - payloadType: Pull_Request_Review
        #       - isReviewState:
        #           reviewState: Approved
        #     then:
        #       - addLabel:
        #           label: Moderator-Approved
onFailure:
onSuccess:
