# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/reduxjs/redux/blob/master/CONTRIBUTING.md#building-redux
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: npm
      directives:
        description: Install Node >=v18.10
        allowPrerelease: true
      settings:
        id: OpenJS.NodeJS
        source: winget
    - resource: NpmDsc/NpmPackage
      id: yarn
      dependsOn:
        - npm
      directives:
        description: Install Yarn
        allowPrerelease: true
      settings:
        Name: 'yarn'
        Global: true
        PackageDirectory: '${WinGetConfigRoot}\..\'
    - resource: YarnDsc/YarnInstall
      dependsOn:
        - yarn
      directives:
        description: Install project dependencies
        allowPrerelease: true
      settings:
        PackageDirectory: '${WinGetConfigRoot}\..\'
  configurationVersion: 0.2.0