# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

##########################################################################################################
# This configuration will install the tools necessary to get started with C++ development on Windows     #
# Reference: https://learn.microsoft.com/cpp/build/vscpp-step-0-installation?view=msvc-170               #
#                                                                                                        #
# This will:                                                                                             #
#     * Enable Developer Mode                                                                            #
#     * Install GitHub Desktop                                                                           #
#     * Install Windows SDK 10.2.22621                                                                   #
#     * Install Visual Studio Community 2022                                                             #
#     * Install the Universal workload to Visual Studio Community 2022                                   #
#     * Instal the NativeDesktop workload to Visual Studio Community 2022                                #
#                                                                                                        #
##########################################################################################################

properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: Enable
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHub Desktop
      directives:
        description: Install GitHub Desktop
        allowPrerelease: true
      settings:
        id: GitHub.GitHubDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VisualStudio
      directives:
        description: Install Visual Studio 2022 Community
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: Workloads NativeDesktop
      dependsOn:
        - VisualStudio
      directives:
        description: Install required VS Workloads (NativeDesktop)
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release                  
        components:
          - Microsoft.VisualStudio.Workload.NativeDesktop
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: Workloads Universal
      dependsOn:
        - VisualStudio
        - Workloads NativeDesktop
      directives:
        description: Install required VS Workloads (Universal)
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release                  
        components:
          - Microsoft.VisualStudio.Workload.Universal
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Windows SDK
      DependsOn:
        - VisualStudio
      directives:
        description: Install Windows SDK
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsSDK.10.0.22621
        source: winget
  configurationVersion: 0.2.0