# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

##########################################################################################################
# This configuration will install the tools necessary to get started with Python development on Windows  #
# Reference: https://learn.microsoft.com/windows/python/beginners                                        #
#                                                                                                        #
# This will:                                                                                             #
#     * Enable Developer Mode                                                                            #
#     * Install GitHub Desktop                                                                           #
#     * Install Python                                                                                   #
#     * Install Visual Studio Code                                                                       #
#                                                                                                        #
##########################################################################################################

properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: Enable
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Python 3.12
      directives:
        description: Install Python 3.12
        allowPrerelease: true
      settings:
        id: Python.Python.3.12
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHub Desktop
      directives:
        description: Install GitHub Desktop
        allowPrerelease: true
      settings:
        id: GitHub.GitHubDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VisualStudio Code
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
  configurationVersion: 0.2.0