name: Markdown Lint

on:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'
  pull_request_target:
    branches:
      - '**'
    tags-ignore:
      - '**'
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

jobs:
  lint:
    name: Check Markdown linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v45
      id: changed-files
      with:
        files: '**/*.md'
    - uses: DavidAnson/markdownlint-cli2-action@v17
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
